import { IJob } from './job.interface';

export const JOBS: IJob[] = [
  {
    id: 1,
    company: 'Scoot',
    logo: './assets/images/logos/scoot.svg',
    logoBg: 'hsl(36, 87%, 49%)',
    position: 'Senior Software Engineer',
    postedAt: '5h ago',
    location: 'United Kingdom',
    website: 'https://example.com/scoot',
  },
  {
    id: 2,
    company: 'Blogr',
    logo: './assets/images/logos/blogr.svg',
    logoBg: 'hsl(12, 79%, 52%)',
    position: 'Haskell and PureScript Dev',
    postedAt: '20h ago',
    location: 'United States',
    website: 'https://example.com/blogr',
  },
  {
    id: 3,
    company: 'Vector',
    logo: './assets/images/logos/vector.svg',
    logoBg: 'hsl(235, 10%, 23%)',
    position: 'Midlevel Backend Developer',
    postedAt: '1d ago',
    location: 'Russia',
    website: 'https://example.com/vector',
  },
  {
    id: 4,
    company: 'Office Lite',
    logo: './assets/images/logos/officelite.svg',
    logoBg: 'hsl(227, 62%, 48%)',
    position: 'Senior Application Engineer',
    postedAt: '2d ago',
    location: 'Japan',
    website: 'https://example.com/officelite',
  },
  {
    id: 5,
    company: 'Pod',
    logo: './assets/images/logos/pod.svg',
    logoBg: 'hsl(216, 46%, 14%)',
    position: 'Remote DevOps Engineer',
    postedAt: '2d ago',
    location: 'Japan',
    website: 'https://example.com/pod',
  },
  {
    id: 6,
    company: 'Creative',
    logo: './assets/images/logos/creative.svg',
    logoBg: 'hsl(295, 55%, 21%)',
    position: 'Desktop Support Manager',
    postedAt: '4d ago',
    location: 'Germany',
    website: 'https://example.com/creative',
  },
  {
    id: 7,
    company: 'Pomodoro',
    logo: './assets/images/logos/pomodoro.svg',
    logoBg: 'hsl(254, 71%, 45%)',
    position: 'iOS Engineer',
    postedAt: '1w ago',
    location: 'United States',
    website: 'https://example.com/pomodoro',
  },
  {
    id: 8,
    company: 'Maker',
    logo: './assets/images/logos/maker.svg',
    logoBg: 'hsl(218, 58%, 31%)',
    position: 'Senior EJB Developer',
    postedAt: '1w ago',
    location: 'United Kingdom',
    website: 'https://example.com/maker',
  },
  {
    id: 9,
    company: 'Coffeeroasters',
    logo: './assets/images/logos/coffeeroasters.svg',
    logoBg: 'hsl(29, 60%, 87%)',
    position: 'Senior Frontend Developer',
    postedAt: '1w ago',
    location: 'Singapore',
    website: 'https://example.com/coffeeroasters',
  },
  {
    id: 10,
    company: 'Mastercraft',
    logo: './assets/images/logos/mastercraft.svg',
    logoBg: 'hsl(0, 0%, 12%)',
    position: 'App & Website Designer',
    postedAt: '2w ago',
    location: 'United States',
    website: 'https://example.com/mastercraft',
  },
  {
    id: 11,
    company: 'Crowdfund',
    logo: './assets/images/logos/crowdfund.svg',
    logoBg: 'hsl(157, 57%, 50%)',
    position: 'Fullstack Developer',
    postedAt: '1mo ago',
    location: 'New Zealand',
    website: 'https://example.com/crowdfund',
  },
  {
    id: 12,
    company: 'Typemaster',
    logo: './assets/images/logos/typemaster.svg',
    logoBg: 'hsl(22, 89%, 52%)',
    position: 'Technical Lead Engineer',
    postedAt: '1mo ago',
    location: 'United Kingdom',
    website: 'https://example.com/typemaster',
  },
  {
    id: 13,
    company: 'Crowdfund',
    logo: './assets/images/logos/crowdfund.svg',
    logoBg: 'hsl(157, 57%, 50%)',
    position: 'Front-end Developer',
    postedAt: '1mo ago',
    location: 'New Zealand',
    website: 'https://example.com/crowdfund',
  },
  {
    id: 14,
    company: 'Coffeeroasters',
    logo: './assets/images/logos/coffeeroasters.svg',
    logoBg: 'hsl(29, 60%, 87%)',
    position: 'Junior Full-Stack Developer',
    postedAt: '1mo ago',
    location: 'Singapore',
    website: 'https://example.com/coffeeroasters',
  },
  {
    id: 15,
    company: 'Blogr',
    logo: './assets/images/logos/blogr.svg',
    logoBg: 'hsl(12, 79%, 52%)',
    position: 'Midweight Front-end Developer',
    postedAt: '1mo ago',
    location: 'United States',
    website: 'https://example.com/blogr',
  },
];
