import { IJob } from './job.interface';

export const JOBS: IJob[] = [
  {
    id: 1,
    company: 'Scoot',
    logo: './assets/images/logos/scoot.svg',
    logoBg: 'hsl(36, 87%, 49%)',
    position: 'Senior Software Engineer',
    postedAt: '5h ago',
    location: 'United Kingdom',
    website: 'https://example.com/scoot',
  },
  {
    id: 2,
    company: 'Blogr',
    logo: './assets/images/logos/blogr.svg',
    logoBg: 'hsl(12, 79%, 52%)',
    position: 'Haskell and PureScript Dev',
    postedAt: '20h ago',
    location: 'United States',
    website: 'https://example.com/blogr',
  },
  {
    id: 3,
    company: 'Vector',
    logo: './assets/images/logos/vector.svg',
    logoBg: 'hsl(235, 10%, 23%)',
    position: 'Midlevel Backend Developer',
    postedAt: '1d ago',
    location: 'Russia',
    website: 'https://example.com/vector',
  },
  {
    id: 4,
    company: 'Office Lite',
    logo: './assets/images/logos/officelite.svg',
    logoBg: 'hsl(227, 62%, 48%)',
    position: 'Senior Application Engineer',
    postedAt: '2d ago',
    location: 'Japan',
    website: 'https://example.com/officelite',
  },
  {
    id: 5,
    company: 'Pod',
    logo: './assets/images/logos/pod.svg',
    logoBg: 'hsl(216, 46%, 14%)',
    position: 'Remote DevOps Engineer',
    postedAt: '2d ago',
    location: 'Japan',
    website: 'https://example.com/pod',
  },
  {
    id: 6,
    company: 'Creative',
    logo: './assets/images/logos/creative.svg',
    logoBg: 'hsl(295, 55%, 21%)',
    position: 'Desktop Support Manager',
    postedAt: '4d ago',
    location: 'Germany',
    website: 'https://example.com/creative',
  },
];
